/**
 * Seeds D1 from src/data/schools.json.
 *
 *   node scripts/seed-d1.mts [--local] [--out FILE]
 *
 * This is a one-time migration, not a recurring job. After this runs, D1 is
 * the source of truth and schools.json stops being authoritative — otherwise
 * you would need a deploy to fix a typo.
 *
 * The one transformation worth knowing about: KHDA's fee year is buried in
 * free text ("Published KHDA range, 2023-2024") and the years are NOT
 * consistent across schools — 195 quote 2023-24, 26 carry no year at all, and
 * the rest scatter from 2019-20 to 2025-26. It is pulled out into its own
 * column here so the site can show it beside every fee, because otherwise the
 * site publishes precise-looking numbers that quietly mean different things.
 */

import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, "..");

const args = process.argv.slice(2);
const LOCAL = args.includes("--local");
const OUT = args[args.indexOf("--out") + 1] ?? join(REPO, ".seed.sql");

interface School {
  slug: string; name: string; area: string; curricula: string[];
  khdaRating: string; feeMinAED: number; feeMaxAED: number; feeNote: string;
  gradeRange: string; website: string; address: string; description: string;
  khdaId: string; phone?: string;
}

/** SQL string literal, or NULL. Zero fees become NULL — the JSON uses 0 as a
 *  sentinel for "unpublished" and every consumer had to remember that. */
const s = (v: string | undefined | null): string =>
  v === undefined || v === null || v === "" ? "NULL" : `'${v.replace(/'/g, "''")}'`;
const n = (v: number | undefined | null): string =>
  v === undefined || v === null || v === 0 ? "NULL" : String(Math.round(v));

/** "Published KHDA range, 2023-2024" -> "2023-2024". NULL when absent. */
function feeYear(note: string | undefined): string | null {
  const m = (note ?? "").match(/(\d{4}-\d{4})/);
  return m ? m[1] : null;
}

const schools: School[] = JSON.parse(
  await readFile(join(REPO, "src", "data", "schools.json"), "utf8")
);

const now = new Date().toISOString();
const lines: string[] = [
  "-- generated by scripts/seed-d1.mts — do not edit",
  "DELETE FROM schools;",
];

for (const x of schools) {
  lines.push(
    `INSERT INTO schools (khda_id, slug, name, area, curricula, khda_rating,` +
      ` fee_min_aed, fee_max_aed, fee_year, fee_note, grade_range, website,` +
      ` phone, address, description, first_seen_at, last_seen_at, updated_at)` +
      ` VALUES (${s(x.khdaId)}, ${s(x.slug)}, ${s(x.name)}, ${s(x.area)},` +
      ` ${s(JSON.stringify(x.curricula))}, ${s(x.khdaRating)},` +
      ` ${n(x.feeMinAED)}, ${n(x.feeMaxAED)}, ${s(feeYear(x.feeNote))}, ${s(x.feeNote)},` +
      ` ${s(x.gradeRange)}, ${s(x.website)}, ${s(x.phone)}, ${s(x.address)},` +
      ` ${s(x.description)}, ${s(now)}, ${s(now)}, ${s(now)});`
  );
}

await writeFile(OUT, lines.join("\n"), "utf8");

const withYear = schools.filter((x) => feeYear(x.feeNote)).length;
console.log(
  `${schools.length} schools -> ${OUT}\n` +
    `  fee year parsed for ${withYear}, absent for ${schools.length - withYear}`
);

const res = spawnSync(
  "npx",
  ["wrangler", "d1", "execute", "dubai-schools", LOCAL ? "--local" : "--remote", `--file=${OUT}`],
  { stdio: "inherit", shell: true, cwd: REPO }
);
process.exit(res.status ?? 1);
