/**
 * Loads src/data/school-principals.json into schools.principal.
 *   node scripts/seed-principals.mts [--local]
 */
import { readFile, writeFile, unlink } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const REPO = join(dirname(fileURLToPath(import.meta.url)), "..");
const LOCAL = process.argv.includes("--local");
const OUT = join(REPO, ".principals.sql");

const rows = JSON.parse(await readFile(join(REPO, "src", "data", "school-principals.json"), "utf8"));
const schools = JSON.parse(await readFile(join(REPO, "src", "data", "schools.json"), "utf8"));
const byName = new Map<string, string>();
for (const s of schools) byName.set(s.name.trim().toLowerCase(), s.khdaId);

const q = (v: string) => `'${v.replace(/'/g, "''")}'`;
const lines = ["-- generated by scripts/seed-principals.mts", "UPDATE schools SET principal = NULL;"];
let written = 0, unmatched = 0;

for (const r of rows) {
  const khdaId = byName.get((r.schoolName ?? "").trim().toLowerCase());
  if (!khdaId) { unmatched++; continue; }
  lines.push(`UPDATE schools SET principal = ${q(r.principal)} WHERE khda_id = ${q(khdaId)};`);
  written++;
}

await writeFile(OUT, lines.join("\n"), "utf8");
console.log(`  ${written} principals queued, ${unmatched} unmatched by name`);
const res = spawnSync("npx", ["wrangler", "d1", "execute", "dubai-schools", LOCAL ? "--local" : "--remote", `--file=${OUT}`], { stdio: "pipe", shell: true, encoding: "utf8" });
try { await unlink(OUT); } catch {}
if (res.status !== 0) { console.error(res.stderr || res.stdout); process.exit(1); }
console.log("  applied");
