/**
 * Loads src/data/grade-fees.json into D1.
 *
 *   node scripts/seed-grade-fees.mts [--local]
 *
 * Rows are matched to a school by name. KHDA prints the same school name on
 * the fact sheet and in the directory listing, so an exact match carries most
 * of them; anything that misses keeps its printed name and a NULL school_id
 * rather than being dropped, and the miss count is reported so a drift in
 * naming is visible rather than silent.
 */

import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, "..");
const LOCAL = process.argv.includes("--local");
const OUT = join(REPO, ".grade-fees.sql");

const rows = JSON.parse(await readFile(join(REPO, "src", "data", "grade-fees.json"), "utf8"));
const schools = JSON.parse(await readFile(join(REPO, "src", "data", "schools.json"), "utf8"));

/** name -> khda_id, so the SQL can resolve school_id by subquery. */
const byName = new Map<string, string>();
for (const s of schools) byName.set(s.name.trim().toLowerCase(), s.khdaId);

const s = (v: unknown): string =>
  v === undefined || v === null || v === "" ? "NULL" : `'${String(v).replace(/'/g, "''")}'`;
const n = (v: unknown): string => (typeof v === "number" && v > 0 ? String(v) : "NULL");
const j = (v: unknown): string =>
  Array.isArray(v) && v.length ? `'${JSON.stringify(v).replace(/'/g, "''")}'` : "NULL";

let matched = 0;
const lines: string[] = ["-- generated by scripts/seed-grade-fees.mts", "DELETE FROM grade_fees;"];

for (const r of rows) {
  const khdaId = byName.get((r.schoolName ?? "").trim().toLowerCase());
  if (khdaId) matched++;
  const schoolId = khdaId
    ? `(SELECT id FROM schools WHERE khda_id = ${s(khdaId)})`
    : "NULL";
  lines.push(
    `INSERT OR REPLACE INTO grade_fees (school_id, center_id, curr_id, grade_id, section_id,` +
      ` school_name, academic_year, curriculum, grade, khda_rating, tuition_aed, total_aed,` +
      ` mandatory, supplies, optional, transport, increase_policy, discounts) VALUES (` +
      `${schoolId}, ${s(r.centerId)}, ${s(r.currId)}, ${s(r.gradeId)}, ${s(r.sectionId)},` +
      ` ${s(r.schoolName)}, ${s(r.academicYear)}, ${s(r.curriculum)}, ${s(r.grade)},` +
      ` ${s(r.khdaRating)}, ${n(r.tuitionAed)}, ${n(r.totalAed)}, ${j(r.mandatory)},` +
      ` ${j(r.supplies)}, ${j(r.optional)}, ${s(r.transport)}, ${s(r.increasePolicy)},` +
      ` ${j(r.discounts)});`
  );
}

await writeFile(OUT, lines.join("\n"), "utf8");
console.log(
  `${rows.length} grade rows -> ${OUT}\n` +
    `  matched to a school: ${matched}   unmatched: ${rows.length - matched}`
);

const res = spawnSync(
  "npx",
  ["wrangler", "d1", "execute", "dubai-schools", LOCAL ? "--local" : "--remote", `--file=${OUT}`],
  { stdio: "inherit", shell: true, cwd: REPO }
);
process.exit(res.status ?? 1);
